/*
 * 이 파일의 값만 바꾸면 청첩장 내용이 갱신됩니다.
 * 사진은 image 폴더에 넣고 "./image/파일명.jpg" 형태로 입력하세요.
 * 빈 문자열("")로 두면 사진 대신 기본 배경이 표시됩니다.
 */
window.INVITATION_DATA = {
  appearance: {
    theme: "sky",
    movieConcept: "none",
    fontSet: "classic",
    heroDecoration: "none",
    heroTextTheme: "auto",
  },
  meta: {
    title: "조성호 ♥ 전지연 결혼합니다",
    description: "2026년 10월 4일 오후 12시 20분, 소중한 분들을 초대합니다.",
    shareImage: "",
  },
  couple: {
    groom: {
      name: "조성호",
      phone: "010-9630-2909",
      parents: "조용석 · 이영희",
      relation: "의 아들",
      birthday: "1995년 10월 4일",
      mbti: "",
      tags: [],
      photo: "",
    },
    bride: {
      name: "전지연",
      phone: "010-9472-4875",
      parents: "전명근 · 박현옥",
      relation: "의 딸",
      birthday: "1997년 9월 29일",
      mbti: "",
      tags: [],
      photo: "",
    },
  },
  displaySettings: {
    showInvitationParents: true,
    showProfileParents: true,
    showProfileBirthdays: true,
  },
  wedding: {
    date: "2026-10-04T12:20:00+09:00",
    displayDate: "2026. 10. 04. 일요일 오후 12시 20분",
    displayDateFormat: "long_ko",
    displayDateCustom: "",
    venue: "그랜드 머큐어 앰배서더 창원",
    hall: "2F 그랜드볼룸홀",
    address: "경상남도 창원시 성산구 원이대로 332",
    mapLinks: [
      { label: "네이버 지도", url: "https://map.naver.com/p/search/%EA%B2%BD%EC%83%81%EB%82%A8%EB%8F%84%20%EC%B0%BD%EC%9B%90%EC%8B%9C%20%EC%84%B1%EC%82%B0%EA%B5%AC%20%EC%9B%90%EC%9D%B4%EB%8C%80%EB%A1%9C%20332" },
      { label: "카카오맵", url: "https://map.kakao.com/link/search/%EA%B2%BD%EC%83%81%EB%82%A8%EB%8F%84%20%EC%B0%BD%EC%9B%90%EC%8B%9C%20%EC%84%B1%EC%82%B0%EA%B5%AC%20%EC%9B%90%EC%9D%B4%EB%8C%80%EB%A1%9C%20332" },
      { label: "티맵", url: "https://www.tmap.co.kr/tmap2/mobile/route.jsp?name=%EA%B2%BD%EC%83%81%EB%82%A8%EB%8F%84%20%EC%B0%BD%EC%9B%90%EC%8B%9C%20%EC%84%B1%EC%82%B0%EA%B5%AC%20%EC%9B%90%EC%9D%B4%EB%8C%80%EB%A1%9C%20332" },
    ],
  },
  hero: {
    eyebrow: "our wedding day",
    introEyebrow: "our wedding day",
    introDate: "",
    introDesign: {
      align: "center",
      eyebrowSize: 11,
      nameSize: 30,
      dateSize: 11,
      eyebrowNameGap: 10,
      nameDateGap: 10,
    },
    image: "",
    video: "",
    activeMedia: "image",
    contentPosition: "top",
  },
  invitation: {
    title: "소중한 분들을 초대합니다",
    paragraphs: [
      "저희 두 사람의 작은 만남이\n진실한 사랑으로 이어졌습니다.",
      "평생 서로를 귀히 여기며\n처음의 설렘을 잃지 않고 살아가겠습니다.",
      "새로운 시작의 자리에 함께하시어\n따뜻한 축복을 나누어 주세요.",
    ],
  },
  sectionTitles: {
    invitation: { en: "Invitation", ko: "" },
    aboutUs: { en: "About Us", ko: "저희를 소개합니다" },
    weddingDay: { en: "Wedding Day", ko: "" },
    location: { en: "Location", ko: "오시는 길" },
    gallery: { en: "Gallery", ko: "갤러리" },
    information: { en: "Information", ko: "식장 안내" },
    attendance: { en: "Rsvp", ko: "참석 의사 전달" },
    weddingSnap: { en: "Guest Album", ko: "예쁘게 빛난 순간, 같이 공유해요!" },
    account: { en: "Account", ko: "마음 전하는 곳" },
    guestbook: { en: "Guestbook", ko: "축하 메시지" },
  },
  sectionDescriptions: {
    attendance: "신랑, 신부에게 참석의사를\n미리 전달할 수 있어요.",
    weddingSnap: "오늘의 추억은 여러분의 한 장에서 완성돼요.\n예식 당일, 아래 버튼으로 가볍게 공유해주세요!",
    account: "참석이 어려우신 분들을 위해\n계좌번호를 안내해 드립니다.",
    guestbook: "따뜻한 마음을 짧게 남겨 주세요.",
  },
  transport: [
    { title: "지하철 · 기차", text: "KTX 창원중앙역 또는 창원역에서 호텔까지 차량으로 약 10분입니다." },
    { title: "버스", text: "창원고속버스터미널에서 호텔까지 차량으로 약 10분입니다. 버스 노선은 변동될 수 있으니 지도 앱에서 최신 경로를 확인해 주세요." },
    { title: "자가용", text: "내비게이션에 '그랜드 머큐어 앰배서더 창원' 또는 주소를 입력해 주세요." },
  ],
  gallery: Array.from({ length: 30 }, () => ""),
  galleryThumbs: Array.from({ length: 30 }, () => ""),
  notices: [
    { title: "식사 안내", text: "예식 전후로 연회장을 편하게 이용해 주세요." },
    { title: "주차 안내", text: "주차 등록은 예식장 로비 키오스크에서 가능합니다." },
  ],
  guestPhotos: {
    eventDate: "2026-10-04",
    previewVisible: true,
    uploadSlug: "wedding-day",
    manageDescription: "이 휴대폰에서 보낸 사진과 영상을 확인하거나 삭제할 수 있습니다.",
    modalGuideTitle: "여러분의 사진첩이 우리 앨범이 됩니다.",
    modalGuideText: "1. 두 사람의 설렘 가득한 스냅\n2. 멋진 입장 & 환한 행진\n3. 가족·친구와의 찰칵 한 컷\n4. 당신의 시선으로 포착한 장면들",
    modalGuideFootnote: "작은 한 컷이 우리에게 큰 선물이 돼요.",
  },
  publicPeriod: {
    openDate: "",
    closeDate: "",
  },
  rsvp: {
    modalGuide: "기차표와 숙소 준비를 위해 필요한 정보입니다.",
    originPlaceholder: "예: 서울역, 창원시 성산구",
    transportOptions: ["자가용", "기차", "버스", "택시", "도보", "직접입력"],
    transportPlaceholder: "예: 자가용, KTX, 버스",
    notesPlaceholder: "교통편이나 숙소 관련 요청을 자유롭게 적어 주세요.",
    accommodationGuide: "숙소 준비를 위해 함께 오는 인원 이름 또는 명수를 적어 주세요.",
  },
  adminDefaults: {
    heroFields: ["eyebrow", "names", "date"],
    signupFields: ["groomName", "brideName", "groomBirthday", "brideBirthday", "weddingDate", "weddingVenue", "weddingHall"],
    welcomeOverlay: {
      eyebrow: "Vivid Vows",
      text: "결혼을 축하드립니다!\n커스텀하여 청첩장을 꾸며보세요.",
      textSize: 30,
      backgroundColor: "#eff7fa",
      cardColor: "#ffffff",
      textColor: "#3b6674",
      overlayOpacity: 94,
      cardOpacity: 88,
      borderColor: "#d8e8ee",
      borderWidth: 1,
      borderRadius: 30,
      shadowEnabled: true,
      shadowColor: "#3b6674",
      shadowOpacity: 24,
    },
    fieldLabels: {
      groomName: "신랑 이름",
      brideName: "신부 이름",
      venue: "식장 이름",
      address: "주소",
    },
  },
  sectionSettings: {
    preWedding: ["invitation", "about-us", "wedding-day", "location", "gallery", "wedding-snap", "information", "attendance", "account", "guestbook"],
    weddingDay: ["invitation", "about-us", "wedding-day", "location", "gallery", "wedding-snap", "information", "attendance", "account", "guestbook"],
  },
  accounts: [
    { side: "신랑측", name: "조성호", relation: "신랑", bank: "국민은행", number: "000000-00-000000" },
    { side: "신랑측", name: "조용석", relation: "신랑 아버지", bank: "신한은행", number: "000-000-000000" },
    { side: "신랑측", name: "이영희", relation: "신랑 어머니", bank: "", number: "" },
    { side: "신부측", name: "전지연", relation: "신부", bank: "우리은행", number: "0000-000-000000" },
    { side: "신부측", name: "전명근", relation: "신부 아버지", bank: "하나은행", number: "000-000000-00000" },
    { side: "신부측", name: "박현옥", relation: "신부 어머니", bank: "", number: "" },
  ],
  ending: {
    image: "",
    text: "저희의 새로운 시작을\n함께해 주셔서 감사합니다.",
  },
};
